<?php
/**
 * Default Lexicon Entries for Babel
 *
 * @package babel
 * @subpackage lexicon
 */
$_lang['babel'] = 'Babel';
$_lang['babel.about'] = 'About Babel';
$_lang['babel.all'] = 'All';
$_lang['babel.context_err_invalid_key'] = '[[+context]] is no valid context key.';
$_lang['babel.context_err_ns'] = 'Context was not specified.';
$_lang['babel.contexts'] = 'Contexts';
$_lang['babel.contexts_desc'] = 'Manage the links between the resources in different contexts/languages in one place. Use the following buttons to edit the links:';
$_lang['babel.contexts_desc_create'] = 'Create a new resource to be linked';
$_lang['babel.contexts_desc_create_multiple'] = 'Create multiple new resources to be linked';
$_lang['babel.contexts_desc_delete'] = 'Delete linked resource';
$_lang['babel.contexts_desc_delete_all'] = 'Delete all linked resources';
$_lang['babel.contexts_desc_link'] = 'Link to this resource and its linked resources';
$_lang['babel.contexts_desc_refresh'] = 'Refresh linked resource(s)';
$_lang['babel.contexts_desc_unlink'] = 'Break link';
$_lang['babel.contexts_desc_update'] = 'Update this linked resource';
$_lang['babel.copy_tv_values'] = 'Copy synchronized TVs to target';
$_lang['babel.create_child_translations'] = 'Create translations of child resources';
$_lang['babel.create_multiple_translations'] = 'Create multiple translations';
$_lang['babel.create_multiple_translations_err_no_contexts'] = 'No contexts available for creating translations.';
$_lang['babel.create_multiple_translations_finished'] = 'The translated resources have been created.';
$_lang['babel.create_translation'] = 'Create translation';
$_lang['babel.create_translation_confirm'] = 'Are you sure you want to create a new translation for this resource to the <b>"[[+context]]"</b> context?';
$_lang['babel.debug_mode'] = 'Debug Mode';
$_lang['babel.delete'] = 'Delete';
$_lang['babel.delete_all'] = 'Delete all';
$_lang['babel.delete_all_translations'] = 'Delete all translations';
$_lang['babel.delete_all_translations_confirm'] = 'Are you sure you want to delete all translations from this resource?';
$_lang['babel.delete_child_translations'] = 'Delete translations of child resources';
$_lang['babel.delete_multiple_translations_finished'] = 'The translated resources have been deleted.';
$_lang['babel.delete_successful'] = 'The translation was successful deleted.';
$_lang['babel.delete_translation'] = 'Delete translation';
$_lang['babel.delete_translation_confirm'] = 'Are you sure you want to delete the translation from this resource in the <b>"[[+context]]"</b> context?';
$_lang['babel.desc'] = 'Managing multilingual system';
$_lang['babel.link_successful'] = 'The resource was successful linked.';
$_lang['babel.link_translation'] = 'Link to existing resource';
$_lang['babel.open'] = 'Open';
$_lang['babel.please_wait'] = 'Please wait …';
$_lang['babel.refresh'] = 'Refresh';
$_lang['babel.refresh_cache'] = 'Clearing the [[+packagename]] cache';
$_lang['babel.refresh_child_translations'] = 'Refresh translations of child resources';
$_lang['babel.refresh_multiple_translations'] = 'Refresh multiple translations';
$_lang['babel.refresh_multiple_translations_err_no_contexts'] = 'No contexts available for refreshing translations.';
$_lang['babel.refresh_multiple_translations_finished'] = 'The translated resources have been refreshed.';
$_lang['babel.refresh_translation'] = 'Refresh translation';
$_lang['babel.refresh_translation_confirm'] = 'Are you sure you want to refresh the translation for this resource in the <b>"[[+context]]"</b> context?';
$_lang['babel.reset'] = 'Reset';
$_lang['babel.resource_err_from_other_context'] = 'Resource [[+resource]] does not exist in context <b>"[[+context]]"</b>.';
$_lang['babel.resource_err_invalid_id'] = '[[+resource]] is no valid resource id.';
$_lang['babel.resource_err_link_of_selflink_not_possible'] = 'A link to a resource itself can not be linked.';
$_lang['babel.search'] = 'Search …';
$_lang['babel.select_context'] = 'Select Context';
$_lang['babel.select_tree_node'] = 'Select a node in the resource tree';
$_lang['babel.settings'] = '<i class="icon icon-cog"><span class="sr-only">Settings</span></i>';
$_lang['babel.settings_desc'] = 'Edit the settings of Babel. You can edit the value of a system setting by double-clicking the ‘Value’ table cell or by right-clicking in the table cell.';
$_lang['babel.success_delete_resource'] = 'The translated resource [[+oldid]] of resource [[+id]] was deleted in context [[+context]].';
$_lang['babel.success_delete_resources'] = 'The translated resources of resource [[+id]] were deleted in all contexts.';
$_lang['babel.success_duplicate_resource'] = 'The translated resource [[+newid]] of resource [[+id]] was created in context [[+context]].';
$_lang['babel.success_sync_resource'] = 'The translated resource [[+newid]] of resource [[+id]] was synchronized in context [[+context]].';
$_lang['babel.success_unlink_resource'] = 'The translated resource [[+oldid]] of resource [[+id]] was unlinked in context [[+context]].';
$_lang['babel.success_unlink_resources'] = 'The translated resources of resource [[+id]] were unlinked in all context.';
$_lang['babel.sync_linked_translations'] = 'Synchronize all translations';
$_lang['babel.sync_linked_translations_target'] = 'Synchronize all translations from the target';
$_lang['babel.systemsetting_key_err_nv'] = 'You can only edit settings with the prefix babel.';
$_lang['babel.systemsetting_usergroup_err_nv'] = 'Only users with a settings permission or settings_babel permission can change the settings.';
$_lang['babel.target_id'] = 'Target ID';
$_lang['babel.target_pagetitle'] = '… or search for the pagetitle of the target';
$_lang['babel.translation_err_could_not_duplicate_resource'] = 'An error occured while trying to create a translation in context [[+context]].';
$_lang['babel.translation_err_could_not_sync_resource'] = 'An error occured while trying to synchronize a translation in context [[+context]].';
$_lang['babel.translation_pending'] = '[translations pending]';
$_lang['babel.tv_caption'] = 'Babel Translation Links';
$_lang['babel.tv_description'] = 'Maintained by Babel plugin. Please do not change!';
$_lang['babel.unlink'] = 'Unlink';
$_lang['babel.unlink_all'] = 'Unlink all';
$_lang['babel.unlink_all_translations'] = 'Unlink all translations';
$_lang['babel.unlink_all_translations_confirm'] = 'Are you sure you want to unlink all translations from this resource?';
$_lang['babel.unlink_child_translations'] = 'Unlink translations of child resources';
$_lang['babel.unlink_multiple_translations_finished'] = 'The translated resources have been unlinked.';
$_lang['babel.unlink_successful'] = 'The translation was successful unlinked.';
$_lang['babel.unlink_translation'] = 'Unlink translation';
$_lang['babel.unlink_translation_confirm'] = 'Are you sure you want to unlink the translation from this resource to the <b>"[[+context]]"</b> context?';
