<?php
/**
 * Default Lexicon Entries for Babel
 *
 * @package babel
 * @subpackage lexicon
 */
$_lang['babel'] = 'Babel';
$_lang['babel.about'] = 'Informazioni su Babel';
$_lang['babel.all'] = 'Tutti';
$_lang['babel.context_err_invalid_key'] = '[[+context]] non &egrave; una chiave di contesto valido.';
$_lang['babel.context_err_ns'] = 'Il contesto non è stato specificato.';
$_lang['babel.contexts'] = 'Contexts';
$_lang['babel.contexts_desc'] = 'Gestire i collegamenti tra le risorse in diversi contesti/lingue in un unico posto. Utilizzate i seguenti pulsanti per modificare i collegamenti:';
$_lang['babel.contexts_desc_create'] = 'Creare una nuova risorsa da collegare';
$_lang['babel.contexts_desc_create_multiple'] = 'Creare più nuove risorse da collegare';
$_lang['babel.contexts_desc_delete'] = 'Cancellare una risorsa collegata';
$_lang['babel.contexts_desc_delete_all'] = 'Eliminare tutte le risorse collegate';
$_lang['babel.contexts_desc_link'] = 'Collegamento a questa risorsa e alle risorse ad essa collegate';
$_lang['babel.contexts_desc_refresh'] = 'Aggiornare le risorse collegate';
$_lang['babel.contexts_desc_unlink'] = 'Interrompere il collegamento';
$_lang['babel.contexts_desc_update'] = 'Aggiornare questa risorsa collegata';
$_lang['babel.copy_tv_values'] = 'Copia le TVs sincronizzate alla destinazione';
$_lang['babel.create_child_translations'] = 'Creare traduzioni di risorse per bambini';
$_lang['babel.create_multiple_translations'] = 'Crea traduzioni multiple';
$_lang['babel.create_multiple_translations_err_no_contexts'] = 'Non sono disponibili contesti per la creazione di traduzioni.';
$_lang['babel.create_multiple_translations_finished'] = 'Le risorse tradotte sono state create.';
$_lang['babel.create_translation'] = 'Crea traduzione';
$_lang['babel.create_translation_confirm'] = 'Sei sicuro di voler creare una nuova traduzione per questa risorsa nel contesto <b>"[[+context]]"</b>?';
$_lang['babel.debug_mode'] = 'Debug Mode';
$_lang['babel.delete'] = 'Cancellare';
$_lang['babel.delete_all'] = 'Cancellare tutti';
$_lang['babel.delete_all_translations'] = 'Cancellare tutte le traduzioni';
$_lang['babel.delete_all_translations_confirm'] = 'Siete sicuri di voler eliminare tutte le traduzioni da questa risorsa?';
$_lang['babel.delete_child_translations'] = 'Eliminare le traduzioni delle risorse figlio';
$_lang['babel.delete_multiple_translations_finished'] = 'Le risorse tradotte sono state eliminate.';
$_lang['babel.delete_successful'] = 'La traduzione è stata cancellata con successo.';
$_lang['babel.delete_translation'] = 'Cancellare la traduzione';
$_lang['babel.delete_translation_confirm'] = 'Si è sicuri di voler cancellare la traduzione da questa risorsa nel contesto <b>"[[+context]]"</b>?';
$_lang['babel.desc'] = 'Gestione di un sistema multilingue';
$_lang['babel.link_successful'] = 'La risorsa è stata collegata con successo.';
$_lang['babel.link_translation'] = 'Collegamento alla risorsa esistente';
$_lang['babel.open'] = 'Aperto';
$_lang['babel.please_wait'] = 'Attendere …';
$_lang['babel.refresh'] = 'Aggiornamento';
$_lang['babel.refresh_cache'] = 'Cancellazione della cache di [[+packagename]]';
$_lang['babel.refresh_child_translations'] = 'Aggiornare le traduzioni delle risorse per bambini';
$_lang['babel.refresh_multiple_translations'] = 'Aggiornare più traduzioni';
$_lang['babel.refresh_multiple_translations_err_no_contexts'] = 'Non sono disponibili contesti per l\'aggiornamento delle traduzioni.';
$_lang['babel.refresh_multiple_translations_finished'] = 'Le risorse tradotte sono state aggiornate.';
$_lang['babel.refresh_translation'] = 'Aggiornamento della traduzione';
$_lang['babel.refresh_translation_confirm'] = 'Si è sicuri di voler aggiornare la traduzione di questa risorsa nel contesto <b>"[[+context]]"</b>?';
$_lang['babel.reset'] = 'Reset';
$_lang['babel.resource_err_from_other_context'] = 'La risorsa [[+resource]] non esiste nel contesto <b>"[[+context]]"</b>.';
$_lang['babel.resource_err_invalid_id'] = '[[+resource]] non &egrave; un id di risorsa valido.';
$_lang['babel.resource_err_link_of_selflink_not_possible'] = 'Un collegamento a una risorsa non può essere collegato.';
$_lang['babel.search'] = 'Ricerca …';
$_lang['babel.select_context'] = 'Selezionare il contesto';
$_lang['babel.select_tree_node'] = 'Selezionare un nodo nell\'albero delle risorse';
$_lang['babel.settings'] = '<i class="icon icon-cog"><span class="sr-only">Impostazioni</span></i>';
$_lang['babel.settings_desc'] = 'Modifica delle impostazioni di Babel. È possibile modificare il valore di un\'impostazione di sistema facendo doppio clic sulla cella della tabella \'Valore\' o facendo clic con il pulsante destro del mouse sulla cella della tabella.';
$_lang['babel.success_delete_resource'] = 'La risorsa tradotta [[+oldid]] della risorsa [[+id]] è stata cancellata nel contesto [[+context]].';
$_lang['babel.success_delete_resources'] = 'Le risorse tradotte della risorsa [[+id]] sono state eliminate in tutti i contesti.';
$_lang['babel.success_duplicate_resource'] = 'Una risorsa tradotta per [[+id]] è stata creata nel contesto [[+context]].';
$_lang['babel.success_sync_resource'] = 'La risorsa tradotta [[+newid]] della risorsa [[+id]] è stata sincronizzata nel contesto [[+context]].';
$_lang['babel.success_unlink_resource'] = 'La risorsa tradotta [[+oldid]] della risorsa [[+id]] è stata scollegata nel contesto [[+context]].';
$_lang['babel.success_unlink_resources'] = 'Le risorse tradotte della risorsa [[+id]] sono state scollegate in tutti i contesti.';
$_lang['babel.sync_linked_translations'] = 'Sincronizzare tutte le traduzioni';
$_lang['babel.sync_linked_translations_target'] = 'Sincronizzare tutte le traduzioni dalla destinazione';
$_lang['babel.systemsetting_key_err_nv'] = 'È possibile modificare solo le impostazioni con il prefisso babel.';
$_lang['babel.systemsetting_usergroup_err_nv'] = 'Solo gli utenti con l\'autorizzazione settings o settings_babel possono modificare le impostazioni.';
$_lang['babel.target_id'] = 'ID di destinazione';
$_lang['babel.target_pagetitle'] = 'Titolo della pagina di destinazione';
$_lang['babel.translation_err_could_not_duplicate_resource'] = 'Si &egrave; verificato un errore durante la creazione della traduzione nel contesto [[+context]].';
$_lang['babel.translation_err_could_not_sync_resource'] = 'Si è verificato un errore durante il tentativo di sincronizzare una traduzione nel contesto [[+context]].';
$_lang['babel.translation_pending'] = '[traduzione in sospeso]';
$_lang['babel.tv_caption'] = 'Links Traduzioni Babel';
$_lang['babel.tv_description'] = 'Gestito dal plugin di Babel. Si prega di non cambiarlo!';
$_lang['babel.unlink'] = 'Unlink';
$_lang['babel.unlink_all'] = 'Scollega tutti i link';
$_lang['babel.unlink_all_translations'] = 'Scollegamento di tutte le traduzioni';
$_lang['babel.unlink_all_translations_confirm'] = 'Siete sicuri di voler scollegare tutte le traduzioni da questa risorsa?';
$_lang['babel.unlink_child_translations'] = 'Disconnettere le traduzioni delle risorse per bambini';
$_lang['babel.unlink_multiple_translations_finished'] = 'Le risorse tradotte sono state scollegate.';
$_lang['babel.unlink_successful'] = 'La traduzione è riuscita a scollegare i collegamenti.';
$_lang['babel.unlink_translation'] = 'Scollegamento della traduzione';
$_lang['babel.unlink_translation_confirm'] = 'Si è sicuri di voler scollegare la traduzione da questa risorsa al contesto <b>"[[+context]]"</b>?';
