<?php
/**
 * Default Lexicon Entries for Babel
 *
 * @package babel
 * @subpackage lexicon
 */
$_lang['babel'] = 'Babel';
$_lang['babel.about'] = 'À propos de Babel';
$_lang['babel.all'] = 'Tous';
$_lang['babel.context_err_invalid_key'] = '[[+context]] n\'est pas une clé de context valide.';
$_lang['babel.context_err_ns'] = 'Le contexte n\'a pas été précisé.';
$_lang['babel.contexts'] = 'Contextes';
$_lang['babel.contexts_desc'] = 'Gérer les liens entre les ressources dans différents contextes/langues en un seul endroit. Utilisez les boutons suivants pour modifier les liens :';
$_lang['babel.contexts_desc_create'] = 'Créer une nouvelle ressource à lier';
$_lang['babel.contexts_desc_create_multiple'] = 'Créer plusieurs nouvelles ressources à lier';
$_lang['babel.contexts_desc_delete'] = 'Supprimer une ressource liée';
$_lang['babel.contexts_desc_delete_all'] = 'Supprimer toutes les ressources liées';
$_lang['babel.contexts_desc_link'] = 'Lien vers cette ressource et ses ressources liées';
$_lang['babel.contexts_desc_refresh'] = 'Actualiser les ressources liées';
$_lang['babel.contexts_desc_unlink'] = 'Interrompre le lien';
$_lang['babel.contexts_desc_update'] = 'Mettre à jour cette ressource liée';
$_lang['babel.copy_tv_values'] = 'Copie des TV synchronisées vers la cible';
$_lang['babel.create_child_translations'] = 'Créer des traductions des ressources destinées aux enfants';
$_lang['babel.create_multiple_translations'] = 'Créer des traductions multiples';
$_lang['babel.create_multiple_translations_err_no_contexts'] = 'Aucun contexte n\'est disponible pour la création de traductions.';
$_lang['babel.create_multiple_translations_finished'] = 'Les ressources traduites ont été créées.';
$_lang['babel.create_translation'] = 'Créer une traduction';
$_lang['babel.create_translation_confirm'] = 'Êtes-vous sûr de vouloir créer une nouvelle traduction pour cette ressource vers <b>"[[+context]]"</b> context ?';
$_lang['babel.debug_mode'] = 'Mode débogage';
$_lang['babel.delete'] = 'Supprimer';
$_lang['babel.delete_all'] = 'Supprimer tout';
$_lang['babel.delete_all_translations'] = 'Supprimer toutes les traductions';
$_lang['babel.delete_all_translations_confirm'] = 'Êtes-vous sûr de vouloir supprimer toutes les traductions de cette ressource ?';
$_lang['babel.delete_child_translations'] = 'Supprimer les traductions des ressources enfants';
$_lang['babel.delete_multiple_translations_finished'] = 'Les ressources traduites ont été supprimées.';
$_lang['babel.delete_successful'] = 'La traduction a été effectuée avec succès.';
$_lang['babel.delete_translation'] = 'Supprimer la traduction';
$_lang['babel.delete_translation_confirm'] = 'Êtes-vous sûr de vouloir supprimer la traduction de cette ressource dans le contexte <b>"[[+context]]"</b> ?';
$_lang['babel.desc'] = 'Gestion d\'un système multilingue';
$_lang['babel.link_successful'] = 'La ressource a été liée avec succès.';
$_lang['babel.link_translation'] = 'Lien vers une ressource existante';
$_lang['babel.open'] = 'Ouvrir';
$_lang['babel.please_wait'] = 'Veuillez patienter …';
$_lang['babel.refresh'] = 'Mise à jour';
$_lang['babel.refresh_cache'] = 'Effacer le cache du [[+packagename]]';
$_lang['babel.refresh_child_translations'] = 'Mise à jour des traductions des ressources destinées aux enfants';
$_lang['babel.refresh_multiple_translations'] = 'Mise à jour de plusieurs traductions';
$_lang['babel.refresh_multiple_translations_err_no_contexts'] = 'Aucun contexte n\'est disponible pour l\'actualisation des traductions.';
$_lang['babel.refresh_multiple_translations_finished'] = 'Les ressources traduites ont été mises à jour.';
$_lang['babel.refresh_translation'] = 'Mise à jour de la traduction';
$_lang['babel.refresh_translation_confirm'] = 'Êtes-vous sûr de vouloir mettre à jour la traduction de cette ressource dans le contexte <b>"[[+context]]"</b> ?';
$_lang['babel.reset'] = 'Réinitialiser';
$_lang['babel.resource_err_from_other_context'] = 'La ressource [[+resource]] n\'existe pas dans le context <b>"[[+context]]"</b>.';
$_lang['babel.resource_err_invalid_id'] = '[[+resource]] n\'est pas un id valide de ressource.';
$_lang['babel.resource_err_link_of_selflink_not_possible'] = 'Un lien vers une ressource elle-même ne peut pas être lié.';
$_lang['babel.search'] = 'Recherche …';
$_lang['babel.select_context'] = 'Sélectionner le contexte';
$_lang['babel.select_tree_node'] = 'Sélectionner un nœud dans l\'arborescence des ressources';
$_lang['babel.settings'] = '<i class="icon icon-cog"><span class="sr-only">Paramètres</span></i>';
$_lang['babel.settings_desc'] = 'Modifier les paramètres de Babel. Vous pouvez modifier la valeur d’un paramètre du système en double-cliquant sur la cellule du tableau ou en cliquant avec le bouton droit de la souris sur la cellule.';
$_lang['babel.success_delete_resource'] = 'La ressource traduite [[+oldid]] de la ressource [[+id]] a été supprimée dans le contexte [[+context]].';
$_lang['babel.success_delete_resources'] = 'Les ressources traduites de la ressource [[+id]] ont été supprimées dans tous les contextes.';
$_lang['babel.success_duplicate_resource'] = 'Une ressource traduite pour [[+id]] a été créée dans le contexte [[+context]].';
$_lang['babel.success_sync_resource'] = 'La ressource traduite [[+newid]] de la ressource [[+id]] a été synchronisée dans le contexte [[+context]].';
$_lang['babel.success_unlink_resource'] = 'La ressource traduite [[+oldid]] de la ressource [[+id]] a été déliée dans le contexte [[+context]].';
$_lang['babel.success_unlink_resources'] = 'Les ressources traduites de la ressource [[+id]] ont été dissociées dans tous les contextes.';
$_lang['babel.sync_linked_translations'] = 'Synchroniser toutes les traductions';
$_lang['babel.sync_linked_translations_target'] = 'Synchroniser toutes les traductions de la cible';
$_lang['babel.systemsetting_key_err_nv'] = 'Vous ne pouvez modifier les paramètres qu’avec le préfixe babel.';
$_lang['babel.systemsetting_usergroup_err_nv'] = 'Seuls les utilisateurs disposant d\'une autorisation settings ou settings_babel peuvent modifier les paramètres.';
$_lang['babel.target_id'] = 'ID de la cible';
$_lang['babel.target_pagetitle'] = '... ou rechercher le titre de la page de la cible';
$_lang['babel.translation_err_could_not_duplicate_resource'] = 'Une erreur est survenue lors de la création de traduction dans le contexte [[+context]].';
$_lang['babel.translation_err_could_not_sync_resource'] = 'Une erreur s\'est produite lors de la synchronisation d\'une traduction dans le contexte [[+context]].';
$_lang['babel.translation_pending'] = '[traduction en attente]';
$_lang['babel.tv_caption'] = 'Liens de traduction de Babel';
$_lang['babel.tv_description'] = 'Mis à jour par le plugin Babel. Veuillez ne pas modifier !';
$_lang['babel.unlink'] = 'Détacher';
$_lang['babel.unlink_all'] = 'Détacher tous';
$_lang['babel.unlink_all_translations'] = 'Détacher toutes les traductions';
$_lang['babel.unlink_all_translations_confirm'] = 'Êtes-vous sûr de vouloir dissocier toutes les traductions de cette ressource ?';
$_lang['babel.unlink_child_translations'] = 'Délier les traductions des ressources de l\'enfant';
$_lang['babel.unlink_multiple_translations_finished'] = 'Les ressources traduites ont été dissociées.';
$_lang['babel.unlink_successful'] = 'La traduction a été déliée avec succès.';
$_lang['babel.unlink_translation'] = 'Annuler la traduction';
$_lang['babel.unlink_translation_confirm'] = 'Êtes-vous sûr de vouloir dissocier la traduction de cette ressource du contexte <b>"[[+context]]"</b> ?';
